server:
  port: 8080
spring:
  application:
    name: reggie                                             #应用名称
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/reggie
      username: root
      password: 123456
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true                        #开启驼峰映射
reggie:
  path: D:\\upload\\
